name: FGO Login System JP

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "45 19 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Gettings files from Repo
        uses: actions/checkout@v2
        with:
          ref: master
          
      - name: Install Requeriments
        run: pip install -r requirements.txt

      - name: Install Requeriments
        run: pip install -r requirements.txt

      - name: Execute main script
        run: |
          python3 main.py
        env:
          userIds: ${{ secrets.GAME_USERIDS }}
          authKeys: ${{ secrets.GAME_AUTHKEYS }}
          secretKeys: ${{ secrets.GAME_SECRETKEYS }}
          fateRegion: ${{ secrets.GAME_REGION }}
          webhookDiscord: ${{ secrets.DISCORD_WEBHOOK }}
          DEVICE_INFO_SECRET: ${{ secrets.DEVICE_INFO_SECRET }}
          USER_AGENT_SECRET: ${{ secrets.USER_AGENT_SECRET }}
