name: FGO Login System NA

on:
  push:
    branches: [NA]
  pull_request:
    branches: [NA]
  schedule:
    - cron: "30 11 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Install Requirements
        run: pip install -r https://raw.githubusercontent.com/itscakebuffet/FGO-Daily-Login/NA/requirements.txt

      - name: Get Files From Repo
        uses: actions/checkout@v2
        with:
          ref: NA

      - name: Execute main script
        run: |
          python3 main.py
        env:
          userIds: ${{ secrets.NA_GAME_USERIDS }}
          authKeys: ${{ secrets.NA_GAME_AUTHKEYS }}
          secretKeys: ${{ secrets.NA_GAME_SECRETKEYS }}
          UserAgent: ${{ secrets.GAME_USERAGENT }}
          fateRegion: ${{ secrets.NA_GAME_REGION }}
          webhookDiscord: ${{ secrets.NA_DISCORD_WEBHOOK }}
